### ISSUE TITLE
Require contributing guidelines

### ISSUE THREAD

**Issue by shynur** [shinkungoo/ECNUCS_for_new#1]
能否考虑将仓库的 目录的结构 和 文件的作用 单独解释一下，或者说你这个仓库的大致架构是怎么样的，以**指导他人如何提交 patch** 为最终目的。

将这些组织成一个单独的文件（比如，`CONTRIBUTING.md`），尽量 简洁易懂、避免过多过密的条规 以提高他人的贡献意愿。

___

顺带一提，你需要一个合适的 license，否则他人难以安心地引用这本书。我推荐 GNU FDL，它是专为文档设计的。

**Comment by ejhshen** [comment]
亲爱的shynur：
您好！
今天更新了README，其中就包括目录结构和对应的文件结构，并且也添加了详细的贡献提交方式和意见提交方式。同时，添加了MIT license。
感谢您的关注。
祝好！
